version: "3"

tasks:
  compile:
    env:
      MIX_ENV: dev
    cmds:
      - mix clean;mix compile
  build:
    env:
      MIX_ENV: dev
    cmds:
      - mix deps.update --all
      - mix clean;mix compile
  test:
    env:
      MIX_ENV: test
    cmds:
      - mix compile
      - mix test
